apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: community-operator-index-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - registry.crgcsa.local:5000/hpestorage/hpe-csi
    source: quay.io/hpestorage/csi-driver-operator:v2.2.1
  - mirrors:
    - registry.crgcsa.local:5000/hpestorage/hpe-csi-driver
    source: quay.io/hpestorage/csi-driver-operator-driver:v2.2.1